### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement numpy==1.23.1

### ISSUE THREAD

**Issue by wyliefoxxx** [volotat/DiffMorph#17]
Running the colab project fails at a number of points, starting with this error:

ERROR: Could not find a version that satisfies the requirement numpy==1.23.1

Unfortunately don't have enough time to troubleshoot this one myself - Anyone else experience this or know a fix, or know what I'm doing wrong? - I am very new to colaboratory

**Comment by kilik128** [comment]
same here

**Comment by volotat** [comment]
The issue was that colab had not supported this version yet. I set a bit yearlier one. It should work fine now.
