### ISSUE TITLE
transition is very gray

### ISSUE THREAD

**Issue by molo32** [volotat/DiffMorph#4]
transition between images is very gray

I use -e 10000 -a 0.4 -m 0.4 -w 0.1

**Comment by VladimirGl** [comment]
https://user-images.githubusercontent.com/3522399/104100842-4b892b80-52ae-11eb-8776-fdb05c661aa9.mp4

also have gray results with different parameters

**Comment by VladimirGl** [comment]
If I use previous repo version (for example commit a1e953d71ad7a691f25a9414c622441d8bfb871f ) result is better, but not sure that it is same as in examples

https://user-images.githubusercontent.com/3522399/104103758-da00ab80-52b4-11eb-838d-b6caa63d4a2c.mp4

**Comment by ftalamo** [comment]
same here!  transition is totally gray

**Comment by volotat** [comment]
There was an issue with loss funtion. Fixed it. Should work fine now. 
Yet, in some cases (when images are too different) gray areas still might appear as the algorithm cannot find good transition between images.
